### ISSUE TITLE
the modal panel shows nothing

### ISSUE THREAD

**Issue by shak1** [paulpflug/vue-hello-world#1]
Hi,
I'm trying to use Vue.js for creating view for my package. As starting point i looked at this package.
When i toggle the package the modal panel has only the div element and doesn't show the hello world message as it should.

p.s : sorry for my poor english

**Comment by paulpflug** [comment]
Hi
thanks for reporting :+1:

I have updated the repository reflecting the changes I made from my own project (opened-files)
could you test it again with the new version? don't forget to run npm install again, as dependencies changed.

p.s : I'm no native speaker, either :smile:

**Comment by shak1** [comment]
Hi,
Now is working :+1: 
Maybe this isn't the right place to ask but can i ask you something. I don't get the point where the model content become the template in hello-world.vue, can you explain me what you are doing.
Thanks

**Comment by paulpflug** [comment]
sure [here](https://github.com/paulpflug/vue-hello-world/blob/master/lib/vue-hello-world.coffee#L20) a empty div is created, which is [then](https://github.com/paulpflug/vue-hello-world/blob/master/lib/vue-hello-world.coffee#L36) linked to the hello-world.vue.

This div is then used as a modal [here](https://github.com/paulpflug/vue-hello-world/blob/master/lib/vue-hello-world.coffee#L58-L59)

**Comment by shak1** [comment]
Now i get it ! thanks
